/* 
 * Spaceflight News
 *
 * Get documentation for the Spaceflight News
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using ApiNews.Client;
using ApiNews.Model;

namespace ApiNews.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IArticlesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// List of articles about space
        /// </summary>
        /// <remarks>
        /// Lists of articles
        /// </remarks>
        /// <exception cref="ApiNews.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Articles</returns>
        Articles ArticlesGet ();

        /// <summary>
        /// List of articles about space
        /// </summary>
        /// <remarks>
        /// Lists of articles
        /// </remarks>
        /// <exception cref="ApiNews.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Articles</returns>
        ApiResponse<Articles> ArticlesGetWithHttpInfo ();
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// List of articles about space
        /// </summary>
        /// <remarks>
        /// Lists of articles
        /// </remarks>
        /// <exception cref="ApiNews.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of Articles</returns>
        System.Threading.Tasks.Task<Articles> ArticlesGetAsync ();

        /// <summary>
        /// List of articles about space
        /// </summary>
        /// <remarks>
        /// Lists of articles
        /// </remarks>
        /// <exception cref="ApiNews.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (Articles)</returns>
        System.Threading.Tasks.Task<ApiResponse<Articles>> ArticlesGetAsyncWithHttpInfo ();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class ArticlesApi : IArticlesApi
    {
        private ApiNews.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ArticlesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ArticlesApi(String basePath)
        {
            this.Configuration = new ApiNews.Client.Configuration { BasePath = basePath };

            ExceptionFactory = ApiNews.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ArticlesApi"/> class
        /// </summary>
        /// <returns></returns>
        public ArticlesApi()
        {
            this.Configuration = ApiNews.Client.Configuration.Default;

            ExceptionFactory = ApiNews.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ArticlesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ArticlesApi(ApiNews.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = ApiNews.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = ApiNews.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ApiNews.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ApiNews.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// List of articles about space Lists of articles
        /// </summary>
        /// <exception cref="ApiNews.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Articles</returns>
        public Articles ArticlesGet ()
        {
             ApiResponse<Articles> localVarResponse = ArticlesGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// List of articles about space Lists of articles
        /// </summary>
        /// <exception cref="ApiNews.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Articles</returns>
        public ApiResponse< Articles > ArticlesGetWithHttpInfo ()
        {

            var localVarPath = "/articles";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ArticlesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Articles>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Articles) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Articles)));
        }

        /// <summary>
        /// List of articles about space Lists of articles
        /// </summary>
        /// <exception cref="ApiNews.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of Articles</returns>
        public async System.Threading.Tasks.Task<Articles> ArticlesGetAsync ()
        {
             ApiResponse<Articles> localVarResponse = await ArticlesGetAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// List of articles about space Lists of articles
        /// </summary>
        /// <exception cref="ApiNews.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (Articles)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Articles>> ArticlesGetAsyncWithHttpInfo ()
        {

            var localVarPath = "/articles";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ArticlesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Articles>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Articles) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Articles)));
        }

    }
}
